version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile

    restart: unless-stopped
    env_file: common.env
    networks:
      - saleor-backend-tier
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - db

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    volumes:
      - monatal-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=monatal
      - POSTGRES_PASSWORD=monatal
    networks:
      - saleor-backend-tier
    ports:
      - "5433:5432"

volumes:
  monatal-data:
    external: true

networks:
  saleor-backend-tier:
    driver: bridge
