# Generated by Django 4.0.2 on 2022-02-12 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identification_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
